---
title: "Water Quality"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

GROUNDWATER
===
```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(highcharter)
library(shiny)
library(leaflet)
library(glue)

groundwater_quality <- read_csv("groundwater_quality.csv")
groundwq_wide <- read_csv("groundwq_wide.csv")

gwq_sites <- read_csv("groundwq_sites.csv")

gwq_sites %>% 
  filter()

g <- gwq_sites %>% 
  select(Region, WellName, Latitude, Longitude) %>%
  distinct() 

g2 <- gwq_sites %>% 
  select(WellName, Latitude, Longitude, CensoredValue, Indicator)

gwq_ecoli <- groundwater_quality %>% 
  filter(Indicator == "E.coli cfu/100ml") %>% 
  group_by(Year) %>% 
  summarise(yearlymeanval = mean(MeanVal))

gwq_nitrogen <- groundwater_quality %>% 
  filter(Indicator == "Nitrate nitrogen g/m3") %>% 
  group_by(Year) %>% 
  summarise(yearlymeanval = mean(MeanVal))

gwq_joined <- gwq_ecoli %>% 
  full_join(gwq_nitrogen, by = "Year") %>% 
  rename(MeanEcoli = yearlymeanval.x,
         MeanNitrogen = yearlymeanval.y)

gwq_regional_sites <- gwq_sites %>% 
  group_by(Region) %>% 
  summarise(TotalSites = n())

mean_by_well <- gwq_sites %>% 
  group_by(Region, WellName, Latitude, Longitude, Indicator, Year) %>% 
  summarise(m = mean(CensoredValue))
  

# mean_vals <- rbind(pmin(mean_groundwq$meanval, 11), pmax(mean_groundwq$meanval-11, 0))
# 
# mean_vals %>%
#   barplot(names.arg=mean_groundwq$Year, col=c("green", "red"), ylim = c(0, 80))
# abline(h = 11, col="red", lty=2)


```

Column {data-width=350}
-------------------------------------

### E. coli and Nitrate Nitrogen Change in New Zealand (2004 - 2019)

```{r}
renderHighchart(
  highchart() %>% 
  hc_yAxis_multiples(
    list(lineWidth = 3, lineColor='blue', title=list(text="E.coli cfu/100ml")),
    list(lineWidth = 3, lineColor="green", title=list(text="Nitrate nitrogen g/m3"))
  ) %>% 
  hc_add_series(data = gwq_joined$MeanEcoli, color='blue', name = "E.coli") %>% 
  hc_add_series(data = gwq_joined$MeanNitrogen, color='green', name = "Nitrate nitrogen", yAxis = 1) %>%
  hc_xAxis(categories = gwq_joined$Year, title = list(text = "Year"))
)
```

### New Zealand Groundwater Quality State by E.coli and Nitrate Nitrogen (2004 - 2019)

```{r}
bootstrapPage(
  tags$style(type = "text/css", "html, body {width:100%;height:100%}"),
  absolutePanel(top = 10, right = 10, 
                selectInput("indicator", label = "", choices = c("E.coli cfu/100ml", "Nitrate nitrogen g/m3"))),
  
  renderLeaflet(
    if(input$indicator == "E.coli cfu/100ml") {
      mean_by_well %>% 
      filter(Indicator == input$indicator) %>% 
      leaflet() %>% 
      setView(lng = "170.1433", lat = "-44.27234", zoom = 9) %>% 
      addTiles() %>% 
      addCircleMarkers(lng = mean_by_well$Longitude, lat = mean_by_well$Latitude,
                       popup = mean_by_well$WellName,
                       color = case_when(is.na(mean_by_well$m) ~ "#b0b0b0", mean_by_well$m == 0 ~ "#02db2e",
                                         mean_by_well$m >= 1 & mean_by_well$m <= 10 ~ "#f62607",
                                         mean_by_well$m >= 11 & mean_by_well$m <= 100 ~ "#a20c06",
                                         TRUE ~ "#5c0404")) %>% 
      addLegend("bottomright", title = "Site Status (2004 -2019)", colors = c("b0b0b0", "#02db2e", "#f62607", "#a20c06", "#5c0404"),
                labels = c("Not Assessed", "No E. coli detected", "Low Risk", "Medium Risk", "High Risk"))

    } else {
      mean_by_well %>% 
      filter(Indicator == input$indicator) %>% 
      leaflet() %>% 
      setView(lng = "170.1433", lat = "-44.27234", zoom = 9) %>% 
      addTiles() %>% 
      addCircleMarkers(lng = mean_by_well$Longitude, lat = mean_by_well$Latitude,
                       popup = mean_by_well$WellName,
                       color = case_when(is.na(mean_by_well$m) ~ "#b0b0b0",
                                         mean_by_well$m >= 0 & mean_by_well$m <= 1 ~ "#ed5b5b",
                                         mean_by_well$m > 1 & mean_by_well$m <= 5.65 ~ "#f62607",
                                         mean_by_well$m > 5.65 & mean_by_well$m <= 11.3 ~ "#a20c06",
                                         TRUE ~ "#5c0404"))%>% 
      addLegend("bottomright", title = "Site Status (2004 -2019)", colors = c("#b0b0b0", "#ed5b5b", "#f62607", "#a20c06", "#5c0404"),
                labels = c("Not Assessed", "No Risk", "Low Risk", "Medium Risk", "High Risk"))
    }
  )
)

```


<!-- ### No. of Wells Sampled -->

<!-- ```{r} -->
<!-- renderValueBox( -->
<!--   valueBox(value = sum(gwq_regional_sites$TotalSites), icon = "fas fa-heart-crack") -->
<!-- ) -->
<!-- ``` -->

<!-- ### No. of Source of Flow Sampled -->

<!-- ```{r} -->
<!-- renderValueBox( -->
<!--   valueBox(value = sum(river_regional_srcs$TotalSites), -->
<!--            icon = "fa-water") -->
<!-- ) -->
<!-- ``` -->
   
Column {data-width=250 .tabset .tabset-fade}
-------------------------------------
   
### E.COLI

```{r}
selectInput("region", label = "Region", choices = c("All", sort(groundwater_quality$Region)), selected = "All")
```   
 
### NITRATE NITROGEN
    
```{r}
selectInput("region", label = "Region", choices = c("All", sort(groundwater_quality$Region)), selected = "All")
```

RIVER
===
Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

### Chart D

```{r}

```
 
 